chat/urls.py
from django.urls import path

from . import views
from .consumers import ChatConsumer

app_name = "chat"
websocket_urlpatterns = [
    path("chat/<uuid:chat_id>", ChatConsumer.as_asgi()),
]



urlpatterns = [
    path("", views.chat_view, name="view"),
    path("list/", views.ChatList.as_view(), name="list"),
    path("contacts/", views.ChatList.as_view(), name="contacts"),
    path("create/<int:user_id>/", views.create_room, name="create"),
    path("join/<uuid:chat_id>/", views.join_room, name="join"),
]

fundraising/urls.py
from django.urls import path
from .views import (
    FundraisingCreateView,
    FundraisingDeleteView,
    FundraisingDetailView,
    FundraisingListView,
    FundraisingUpdateView,
    FundraisingCategoryListView,
    Donate,
    MyFundraisingDetailView,
    MyFundraisingListView,
    fundraising_view,
    my_fundraising_view,
    complete,
)

app_name = "fundraising"
urlpatterns = [
    path("fundraising/view", fundraising_view, name="view"),
    path("fundraising/view/my", my_fundraising_view, name="my-view"),
    path("fundraising/", FundraisingListView.as_view(), name="list"),
    path("fundraising/my", MyFundraisingListView.as_view(), name="my-list"),
    path(
        "fundraising/category/", FundraisingCategoryListView.as_view(), name="category"
    ),
    path("fundraising/add", FundraisingCreateView.as_view(), name="add"),
    path("fundraising/<int:pk>/", FundraisingDetailView.as_view(), name="detail"),
    path(
        "fundraising/<int:pk>/my", MyFundraisingDetailView.as_view(), name="my-detail"
    ),
    path(
        "fundraising/<int:pk>/change/", FundraisingUpdateView.as_view(), name="update"
    ),
    path("fundraising/<int:pk>/delete", FundraisingDeleteView.as_view(), name="delete"),
    path("donate/<int:fundraising_id>/", Donate.as_view(), name="donate"),
    path("fundraising/<int:pk>/complete/", complete, name="complete"),
]

tspp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from orders.views import index


from django.views.generic import ListView
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from typing import List


UserModel = get_user_model()


class UsersListView(LoginRequiredMixin, ListView):
    http_method_names = [
        "get",
    ]

    def get_queryset(self):
        return UserModel.objects.all().exclude(id=self.request.user.id)

    def render_to_response(self, context, **response_kwargs):
        users: List[AbstractBaseUser] = context["object_list"]

        data = [{"username": user.get_username(), "pk": str(user.pk)} for user in users]
        return JsonResponse(data, safe=False, **response_kwargs)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("account.urls"), name="account"),
    path("cabinet/", include("orders.urls"), name="orders"),
    path("cabinet/", include("fundraising.urls"), name="fundraising"),
    path("", index, name="home"),
    path("chat/", include("chat.urls"), name="chat"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/my_fundraising/my_fundraising_detail.html
<div class="is-flex is-flex-direction-column is-justify-content-space-betwee container box mt-2">
    <div class="content">
        <div class="is-flex is-justify-content-space-between">
            <div>
                <p class="title">{{object.title}}</p>
                <p class="subtitle">{{object.info}}</p>
            </div>
            <div class="is-flex is-flex-direction-column">
                <p class="title is-3">{{object.price}} UAH</p>
                <a hx-get="{%url 'fundraising:donate' fundraising_id=object.pk%}" 
                    hx-swap="innerHTML" 
                    hx-target="#content-detail" 
                    class="is-primary button">Задонатити</a>
            </div>
            
        </div>

        <p class="subtitle">Категорія: <a>{{object.category.name}}</a></p>
    </div>
    <div class="columns">
        <div class="content is-flex is-flex-direction-column column p-4">
            <div class="is-flex gap-10 is-align-items-center">
                <img class="is-rounded" src="{{object.squad.get_photo}}" height="64" width="64">
                <p>Автор: <a class="is-underlined">{{object.squad.squad_name}}</a></p>
            </div>
        </div>
        <div class="column is-3 p-4">
            <div class="is-flex gap-6 is-flex-direction-column ">
                <a  hx-get="{%url 'fundraising:delete' pk=object.pk%}" 
                    hx-target="#place-for-modal" 
                    hx-swap="innerHTML"
                    class="button is-danger">Видалити збір</a>
                <a  hx-get="{%url 'fundraising:update' pk=object.pk%}" 
                    hx-target="#content-detail" 
                    hx-swap="innerHTML"
                    class="button is-info">Редагувати</a>
                <div class="dropdown is-hoverable">
                    <div class="dropdown-trigger">
                        <button class="button" aria-haspopup="true" aria-controls="dropdown-menu">
                            <span>Більше</span>
                            <span class="icon is-small">
                              <i class="fas fa-angle-down" aria-hidden="true"></i>
                            </span>
                          </button>
                        </div>
                        <div class="dropdown-menu" id="dropdown-menu" role="menu">
                          <div class="dropdown-content">
                            <a class="dropdown-item">
                                <a class="dropdown-item" hx-get="{%url 'fundraising:complete' pk=object.pk%}">
                                    Закрити збір
                                </a>
                            </a>
                          </div>
                        </div>
                      </div>
            </div>
        </div>
    </div>
    {%with donated_sum=object.get_donated_amount%}
    <div class="is-flex is-flex-direction-column">
        <p class="title is-5">Вже задонатили {{donated_sum}} ₴</p>
        <progress class="progress is-primary" 
        value="{{donated_sum| stringformat:'d'}}" 
        max="{{object.price| stringformat:'d'}}"></progress>
    </div>
    {% endwith %}
    <div class="is-flex is-justify-content-flex-end">
        <p class="has-text-left subtitle is-6 mt-2">{{object.created_at|date:'d.m.Y H:i'}}</p>
    </div>
    
    
    <div id="place-for-modal"></div>
    
    
</div>

templates/my_fundraising/my_fundraising_list.html
<ul class="is-overflowed" id="side-ul">
    {%for order in object_list%}
        <li class="mb-2">
            <div class="card is-clickable p-2 card-hovered" hx-get="{%url 'fundraising:my-detail' pk=order.id%}" hx-target="#content-detail" hx-swap="innerHTML" hx-trigger="click">
                    
                    <div class="card-content">
                        <div class="is-flex is-flex-direction-row is-justify-content-space-between">
                            <div>
                                <p class="title is-4">{{order.title}}</p>
                                <p class="subtitle is-6">{{order.info|truncatechars:40}}</p>
                                <p class="title is-5">{{order.price}} UAH</p>
                            </div>
                            <div>
                                {%if order.is_completed%}
                                <p class="tag is-primary">Закрито</p>
                                <p>В: {{order.completed_at|date:'d.m.Y'}}</p>
                                <p>Сума: {{order.get_donated_amount}} ₴</p>
                                {%else%}
                                    <p class="tag is-info">В процесі</p>
                                {%endif%}
                            </div>
                        </div>
                    </div>
            </div>
        </li>
    {%empty%}
        <p>Нажаль тут нічого немає</p>
    {%endfor%}
</ul>
{%if page_obj.has_next%}
    <button class="button is-primary" hx-get="{{request.path}}?page={{page_obj.next_page_number}}" hx-trigger="click" hx-swap="outerHTML" hx-targe="side-ul">Далі...</button>
{%endif%}

templates/my_fundraising/my_fundraising_view.html
<div class="columns">



    <div class="column is-3 is-flex is-flex-direction-column">
            <div class="is-sticked box mt-2" style="z-index:10;">
              <p class="subtitle is-4 has-text-centered is-sticked">Мої Збори</p>
                <div class="field">
                    <p class="control has-icons-left">
                      <input class="input" type="text" placeholder="Пошук" hx-get="{%url 'fundraising:my-list'%}" 
                      name="search" 
                      hx-target="#side-menu"
                      hx-swap="innerHTML"
                      hx-trigger="keyup changed delay:1s">
                      <span class="icon is-small is-left">
                        <i class="fas fa-search"></i>
                      </span>
                    </p>
                  </div>
            </div>
            
            <aside id="side-menu" style="overflow-y:auto;" class="content-size">
                    <div hx-get="{%url 'fundraising:my-list'%}" hx-trigger="load" hx-target="#side-menu" hx-swap="innerHTML">
                    </div>
            </aside>
    </div>
    <div class="column content-column" id="content-detail" style="overflow-y:auto;">
        <div class="columns is-vcentered">
          <div class="has-text-centered column ">
            <p>Будь-ласка виберіть щось</p>
          </div>
        </div>
    </div>

    
</div>