account/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import (
    UserLoginView,
    VolunterCategory,
    user_change,
    user_signup,
    user_signup_next,
    user_signup_complete,
    user_profile,
    squad_view,
    SquadDetailView,
    SquadListView,
    SquadCategory,
    volunter_view,
    VolunterDetailView,
    VolunterListView,
)

app_name = "account"

urlpatterns = [
    # auth
    path("login/", UserLoginView.as_view(next_page="/"), name="login"),
    path("logout/", LogoutView.as_view(next_page="/account/login"), name="logout"),
    path("signup/next/<int:pk>/", user_signup_next, name="signup-next"),
    path("signup/complete", user_signup_complete, name="signup-complete"),
    path("signup/", user_signup, name="signup"),
    # profile
    path("profile/", user_profile, name="profile"),
    path("profile/update", user_change, name="profile-update"),
    # squad
    path("squad/view/", squad_view, name="squad-view"),
    path("squad/category/", SquadCategory.as_view(), name="squad-category"),
    path("squad/<int:pk>/", SquadDetailView.as_view(), name="squad-detail"),
    path("squad/", SquadListView.as_view(), name="squad-list"),
    # volunters
    path("volunter/view/", volunter_view, name="volunter-view"),
    path("volunter/category/", VolunterCategory.as_view(), name="volunter-category"),
    path("volunter/<int:pk>/", VolunterDetailView.as_view(), name="volunter-detail"),
    path("volunter/", VolunterListView.as_view(), name="volunter-list"),
]

chat/urls.py
from django.urls import path

from . import views
from .consumers import ChatConsumer

app_name = "chat"
websocket_urlpatterns = [
    path("chat/<uuid:chat_id>", ChatConsumer.as_asgi()),
]



urlpatterns = [
    path("", views.chat_view, name="view"),
    path("list/", views.ChatList.as_view(), name="list"),
    path("contacts/", views.ChatList.as_view(), name="contacts"),
    path("create/<int:user_id>/", views.create_room, name="create"),
    path("join/<uuid:chat_id>/", views.join_room, name="join"),
]

fundraising/urls.py
from django.urls import path
from .views import (
    FundraisingCreateView,
    FundraisingDeleteView,
    FundraisingDetailView,
    FundraisingListView,
    FundraisingUpdateView,
    FundraisingCategoryListView,
    Donate,
    MyFundraisingDetailView,
    MyFundraisingListView,
    fundraising_view,
    my_fundraising_view,
    complete,
)

app_name = "fundraising"
urlpatterns = [
    path("fundraising/view", fundraising_view, name="view"),
    path("fundraising/view/my", my_fundraising_view, name="my-view"),
    path("fundraising/", FundraisingListView.as_view(), name="list"),
    path("fundraising/my", MyFundraisingListView.as_view(), name="my-list"),
    path(
        "fundraising/category/", FundraisingCategoryListView.as_view(), name="category"
    ),
    path("fundraising/add", FundraisingCreateView.as_view(), name="add"),
    path("fundraising/<int:pk>/", FundraisingDetailView.as_view(), name="detail"),
    path(
        "fundraising/<int:pk>/my", MyFundraisingDetailView.as_view(), name="my-detail"
    ),
    path(
        "fundraising/<int:pk>/change/", FundraisingUpdateView.as_view(), name="update"
    ),
    path("fundraising/<int:pk>/delete", FundraisingDeleteView.as_view(), name="delete"),
    path("donate/<int:fundraising_id>/", Donate.as_view(), name="donate"),
    path("fundraising/<int:pk>/complete/", complete, name="complete"),
]

orders/urls.py
from django.urls import path, re_path
from .views import (
    MyOrdersDetailView,
    MyOrdersListView,
    my_orders_view,
    order_view,
    OrdersListView,
    OrdersDetailView,
    OrdersDeleteView,
    OrdersCreateView,
    OrdersUpdateView,
    OrdersCategoryListView,
    take_order,
    untake_order,
    remove_contractor,
    mark_completed,
)

app_name = "orders"
urlpatterns = [
    path("orders/view", order_view, name="view"),
    path("orders/view/my", my_orders_view, name="my-view"),
    path("orders/", OrdersListView.as_view(), name="list"),
    path("orders/my/", MyOrdersListView.as_view(), name="my-list"),
    path("orders/category", OrdersCategoryListView.as_view(), name="category"),
    path("orders/add", OrdersCreateView.as_view(), name="add"),
    path("orders/<int:pk>/", OrdersDetailView.as_view(), name="detail"),
    path("orders/<int:pk>/my/", MyOrdersDetailView.as_view(), name="my-detail"),
    path("orders/<int:pk>/change/", OrdersUpdateView.as_view(), name="update"),
    path("orders/<int:pk>/delete/", OrdersDeleteView.as_view(), name="delete"),
    path("orders/<int:pk>/take/", take_order, name="take"),
    path("orders/<int:pk>/untake/", untake_order, name="untake"),
    path(
        "orders/<int:pk>/untake_contractor/",
        remove_contractor,
        name="untake-contractor",
    ),
    path("orders/<int:pk>/complete/", mark_completed, name="complete"),
]

tspp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from orders.views import index


from django.views.generic import ListView
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from typing import List


UserModel = get_user_model()


class UsersListView(LoginRequiredMixin, ListView):
    http_method_names = [
        "get",
    ]

    def get_queryset(self):
        return UserModel.objects.all().exclude(id=self.request.user.id)

    def render_to_response(self, context, **response_kwargs):
        users: List[AbstractBaseUser] = context["object_list"]

        data = [{"username": user.get_username(), "pk": str(user.pk)} for user in users]
        return JsonResponse(data, safe=False, **response_kwargs)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("account.urls"), name="account"),
    path("cabinet/", include("orders.urls"), name="orders"),
    path("cabinet/", include("fundraising.urls"), name="fundraising"),
    path("", index, name="home"),
    path("chat/", include("chat.urls"), name="chat"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%block head_links%}
        {% include "head.html" %}
    {%endblock%}
    <title>{{title}}</title>
</head>
<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}' hx-ext="ws">
    {% if messages %}
        {% for message in messages %}
        <div class="notification is-{{message.tags}}">
            <button class="delete"></button>
            {{message}}
        </div>
        {% endfor %}
    {% endif %}
    <header>
        {%block header%}
        {%endblock%}
    </header>
    <article class="has-background-light px-2">
        {%block content%}
            {%endblock%}
    </article>
    <footer>
        {%block footer%}
        {%endblock%}
    </footer>

    {%block scripts%}
        {% include "scripts.html" %}
    {% endblock %}
    
</body>
</html>

templates/base_layout.html
{% extends "base.html" %}
{%load static%}
{%block header%}
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <figure class="image is-32x32">
          <img src="{%static 'img/logo.svg'%}" >
        </figure>
      </a>
  
      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbar">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
  
    <div id="navbar" class="navbar-menu">
      {%if request.user.is_authenticated%}
      <div class="navbar-start">
        <a class="navbar-item" hx-get="{%url 'orders:view'%}" hx-target="#content-div" hx-swap="innerHTML">
          Запити
        </a>
  
        <a class="navbar-item" hx-get="{%url 'fundraising:view'%}" hx-target="#content-div" hx-swap="innerHTML">
          Збори коштів
        </a>

        <a class="navbar-item" hx-get="{%url 'account:squad-view'%}" hx-target="#content-div" hx-swap="innerHTML">
            Військові бригади
        </a>

        <a class="navbar-item" hx-get="{%url 'account:volunter-view'%}" hx-target="#content-div" hx-swap="innerHTML">
            Фонди
        </a>
      </div>

      <div class="navbar-end">

        {%if request.user.role.title == "Squad"%}
        <div class="navbar-item">
            <div class="buttons">
                <a class="button is-info" hx-get="{%url 'orders:add'%}" hx-swap="innerHTML" hx-target="#content-div">Створити запит</a>
                <a class="button is-primary" hx-get="{%url 'fundraising:add'%}"  hx-swap="innerHTML" hx-target="#content-div">Створити збір</a>
            </div>
        </div>
        {%endif%}

        <div class="navbar-item">
            <div class="buttons">
                <a class="button is-rounded is-small">
                    <span class="icon is-small">
                        <i class="fa-regular fa-bell"></i>
                    </span>
                </a>
                <a class="button is-rounded is-small" hx-get="{%url 'chat:view'%}" hx-swap="innerHTML" hx-target="#content-div">
                    <span class="icon is-small">
                        <i class="fa-regular fa-envelope"></i>
                    </span>
                </a>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link is-arrowless button is-rounded">
                            <span class="icon is-small">
                                <i class="fa-regular fa-user"></i>
                            </span>
                    </a>
                    <div class="navbar-dropdown">
                      <div class="navbar-item is-flex is-flex-direction-row is-justify-content-space-between">
                        <p class="is-flex is-flex-wrap-wrap">{{request.user.get_profile}}</p>
                        <figure class="image is-32x32">
                          <img src="{{request.user.get_photo}}" class="is-rounded">
                        </figure>
                      </div>
                      <a class="navbar-item" hx-get="{%url 'account:profile'%}" hx-swap="innerHTML" hx-target="#content-div">
                        Профіль
                      </a>
                      <a class="navbar-item" hx-get="{%url 'orders:my-view'%}" hx-swap="innerHTML" hx-target="#content-div">
                        Мої запити
                      </a>
                      {%if request.user.role.title == "Squad"%}
                        <a class="navbar-item" hx-get="{%url 'fundraising:my-view'%}" hx-swap="innerHTML" hx-target="#content-div">
                          Мої збори
                        </a>
                      {%endif%}
                      <hr class="navbar-divider">
                      <form action="{%url 'account:logout'%}" method="POST" class="navbar-item">
                        {% csrf_token %}
                        <button class=" is-danger button m-2" type="submit">
                            Вийти 
                        </button>
                      </form>
                      
                    </div>
                </div>
            </div>
        </div>

      </div>
      {%else%}
        <div class="navbar-start">
          <a class="navbar-item">
            Про нас
          </a>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
                <a class="button is-primary is-outlined" href="{%url 'account:login'%}">Увійти</a>
                <a class="button is-primary" href="{%url 'account:signup'%}">Зареєструватись</a>
            </div>
        </div>
      {%endif%}
    </div>
</nav>
{%endblock%}

{%block content%}
<div id="content-div" >

</div>
{%endblock%}

{%block footer%}
<div class="box content is-flex is-justify-content-space-between is-align-items-center has-background-dark p-1">
  <div class="buttons has-text-white m-0">
    <a class="button is-rounded is-info is-outlined is-small" href="https://github.com/AstralMortem/Warrior-TKD">
    <span class="icon is-small">
      <i class="fa-brands fa-github"></i>
    </span>
    </a>
  </div>
  <p class="title is-5 has-text-white m-0">Автори сайту: МІСКЛІКЕРИ</p>
  <p class="title is-5 has-text-white">Copyright © 2024</p>
</div>
{%endblock%}

templates/head.html
{% load static %}

<link rel="stylesheet" href="{%static 'css/bulma.min.css'%}">
<link rel="stylesheet" href="{%static 'css/style.css'%}">

templates/index.html
{% extends "base_layout.html" %}
{%load static%}

{%block content%}
<div id="content-div" >
    {%if redirect_path%}
        <div hx-get="{{redirect_path}}" hx-trigger="load" hx-target="#content-div" hx-swap="innerHTML"></div> 
    {%endif%}

    <nav class="level card p-4 my-2">
    <div class="level-item has-text-centered">
        <div>
        <p class="heading">К-ть волонтерів</p>
        <p class="title">3,456</p>
        </div>
    </div>
    <div class="level-item has-text-centered">
        <div>
        <p class="heading">К-ть військових</p>
        <p class="title">688</p>
        </div>
    </div>
    <div class="level-item has-text-centered">
        <div>
        <p class="heading">К-ть виконаних запитів</p>
        <p class="title">456</p>
        </div>
    </div>
    <div class="level-item has-text-centered">
        <div>
        <p class="heading">Найдорожчий закритий збір</p>
        <p class="title">30M. ₴</p>
        </div>
    </div>
    </nav>

    <div class="is-flex is-flex-direction-column my-2" style="margin:0 8%;">
        <div class="columns is-align-items-center">
            <div class="column">
                <figure class="image">
                    <img src="{% static 'img/drone.webp' %}" style="border-radius:15px;">
                </figure>
                </div>
            <div class="column px-6">
                <div class="card p-4 is-flex is-flex-direction-column ">
                    <p class="title has-text-centered">Хто ми?</p>
                    <figure class="image is-128x128 is-align-self-center">
                            <img src="{%static 'img/logo.svg'%}" >
                        </figure>
                    <p class="subtitle has-text-centered">MAVU Military Association of Volunteers of Ukraine</p>

                        
                        
                    <p>Платформа MAVU була створена після початку повномасштабного вторгнення країни-агресора на територію нашої держави, 4-ма молодими студентами з НУБІП.</p>
                </div>
            </div>
        </div>
        <div class="columns is-align-items-center">
            <div class="column is-half px-6">
                <div class="card p-4">
                    <p class="title has-text-centered">Для чого ми?</p>
                    <p>Дана платформа створена виключно для наших захисників, що потребують невідкладної допомоги. Розробники платформи дали змогу військовим швидко і оперативно розміщувати запити на необхідне обладнання, автомобілі, БПЛА, та все інше, що наблизить нашу перемогу. Волонтери, які зареєстровані на MAVU , можуть швидко приймати замовлення та відкривати збори, аби якнайшвидше допомогти справжнім героям українського народу. </p>
                </div>
            </div>
            <div class="column is-half">
                <figure class="image">
                    <img src="{%static 'img/army.webp'%}" style="border-radius:15px;">
                </figure>
                </div>
        </div>
        <div class="columns is-align-items-center">
            <div class="column">
                <figure class="image">
                    <img src="{% static 'img/volunters.jpg' %}" style="border-radius:15px;">
                </figure>
                </div>
            <div class="column px-6">
                <div class="card p-4">
                    <p class="title has-text-centered">Перші результати</p>
                    <p>Під час пілотного запуску, платформа швидко отримала популярність, багато волонтерів та військових долучились до нас. В перший же день ми закрили збір на <b>1000000₴</b> і тим самим врятувавши життя    наших бійців.</p>
                    <p>Наша сила - у єднанні, а наша перемога - у вашій підтримці. 
                        Спільно ми зможемо пережити ці випробування та перемогти.<b>Слава Україні!</b> </p>
                </div>
            </div>
        </div>
    </div>

    <div class="card p-4 my-6">
        <p class="title has-text-centered ">Спонсори</p>
    <nav class="level mt-4">
        <div class="level-item has-text-centered">
            <div class="is-flex is-flex-direction-column is-justify-content-space-around is-align-items-center">
                <figure class="image is-64x64">
                    <img src="{% static 'img/sponsor/1.svg'%}" alt="1">
                </figure>
                <p class="title is-4">3 ОШБ</p>
            </div>
        </div>
        <div class="level-item has-text-centered">
            <div class="is-flex is-flex-direction-column is-justify-content-space-around is-align-items-center">
                <figure class="image is-64x64">
                    <img src="{% static 'img/sponsor/2.svg'%}" alt="1">
                </figure>
                <p class="title is-4">МО України</p>
            </div>
        </div>
        <div class="level-item has-text-centered">
            <div class="is-flex is-flex-direction-column is-justify-content-space-around is-align-items-center" >
                <figure class="image is-64x64">
                    <img src="{% static 'img/sponsor/3.svg'%}" alt="1">
                </figure>
                <p class="title is-4">Фонд повернись живим</p>
            </div>
        </div>
        <div class="level-item has-text-centered">
            <div class="is-flex is-flex-direction-column is-justify-content-space-around is-align-items-center">
                <figure class="image is-64x64">
                    <img src="{% static 'img/sponsor/4.svg'%}" alt="1">
                </figure>
                <p class="title is-4">Дія</p>
            </div>
        </div>
    </nav>
</div>
    
</div>

<script src="{% static 'js/ant.js' %}"></script>

<script>new Ant()</script>
{%endblock%}

templates/login_layout.html
{% extends "base.html" %}

<section class="hero is-fullheight is-primary">
{%block content%}
{%endblock%}
</section>

templates/scripts.html
{%load static%}


<script src="https://kit.fontawesome.com/9eabf3b90b.js" crossorigin="anonymous"></script>

<script src="{%static 'js/htmx.js' %}"></script>

<script src="{%static 'js/script.js' %}"></script>