account/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import (
    UserLoginView,
    VolunterCategory,
    user_change,
    user_signup,
    user_signup_next,
    user_signup_complete,
    user_profile,
    squad_view,
    SquadDetailView,
    SquadListView,
    SquadCategory,
    volunter_view,
    VolunterDetailView,
    VolunterListView,
)

app_name = "account"

urlpatterns = [
    # auth
    path("login/", UserLoginView.as_view(next_page="/"), name="login"),
    path("logout/", LogoutView.as_view(next_page="/account/login"), name="logout"),
    path("signup/next/<int:pk>/", user_signup_next, name="signup-next"),
    path("signup/complete", user_signup_complete, name="signup-complete"),
    path("signup/", user_signup, name="signup"),
    # profile
    path("profile/", user_profile, name="profile"),
    path("profile/update", user_change, name="profile-update"),
    # squad
    path("squad/view/", squad_view, name="squad-view"),
    path("squad/category/", SquadCategory.as_view(), name="squad-category"),
    path("squad/<int:pk>/", SquadDetailView.as_view(), name="squad-detail"),
    path("squad/", SquadListView.as_view(), name="squad-list"),
    # volunters
    path("volunter/view/", volunter_view, name="volunter-view"),
    path("volunter/category/", VolunterCategory.as_view(), name="volunter-category"),
    path("volunter/<int:pk>/", VolunterDetailView.as_view(), name="volunter-detail"),
    path("volunter/", VolunterListView.as_view(), name="volunter-list"),
]

chat/urls.py
from django.urls import path

from . import views
from .consumers import ChatConsumer

app_name = "chat"
websocket_urlpatterns = [
    path("chat/<uuid:chat_id>", ChatConsumer.as_asgi()),
]



urlpatterns = [
    path("", views.chat_view, name="view"),
    path("list/", views.ChatList.as_view(), name="list"),
    path("contacts/", views.ChatList.as_view(), name="contacts"),
    path("create/<int:user_id>/", views.create_room, name="create"),
    path("join/<uuid:chat_id>/", views.join_room, name="join"),
]

orders/urls.py
from django.urls import path, re_path
from .views import (
    MyOrdersDetailView,
    MyOrdersListView,
    my_orders_view,
    order_view,
    OrdersListView,
    OrdersDetailView,
    OrdersDeleteView,
    OrdersCreateView,
    OrdersUpdateView,
    OrdersCategoryListView,
    take_order,
    untake_order,
    remove_contractor,
    mark_completed,
)

app_name = "orders"
urlpatterns = [
    path("orders/view", order_view, name="view"),
    path("orders/view/my", my_orders_view, name="my-view"),
    path("orders/", OrdersListView.as_view(), name="list"),
    path("orders/my/", MyOrdersListView.as_view(), name="my-list"),
    path("orders/category", OrdersCategoryListView.as_view(), name="category"),
    path("orders/add", OrdersCreateView.as_view(), name="add"),
    path("orders/<int:pk>/", OrdersDetailView.as_view(), name="detail"),
    path("orders/<int:pk>/my/", MyOrdersDetailView.as_view(), name="my-detail"),
    path("orders/<int:pk>/change/", OrdersUpdateView.as_view(), name="update"),
    path("orders/<int:pk>/delete/", OrdersDeleteView.as_view(), name="delete"),
    path("orders/<int:pk>/take/", take_order, name="take"),
    path("orders/<int:pk>/untake/", untake_order, name="untake"),
    path(
        "orders/<int:pk>/untake_contractor/",
        remove_contractor,
        name="untake-contractor",
    ),
    path("orders/<int:pk>/complete/", mark_completed, name="complete"),
]

tspp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from orders.views import index


from django.views.generic import ListView
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from typing import List


UserModel = get_user_model()


class UsersListView(LoginRequiredMixin, ListView):
    http_method_names = [
        "get",
    ]

    def get_queryset(self):
        return UserModel.objects.all().exclude(id=self.request.user.id)

    def render_to_response(self, context, **response_kwargs):
        users: List[AbstractBaseUser] = context["object_list"]

        data = [{"username": user.get_username(), "pk": str(user.pk)} for user in users]
        return JsonResponse(data, safe=False, **response_kwargs)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("account.urls"), name="account"),
    path("cabinet/", include("orders.urls"), name="orders"),
    path("cabinet/", include("fundraising.urls"), name="fundraising"),
    path("", index, name="home"),
    path("chat/", include("chat.urls"), name="chat"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from utils.models import IOrder


class Category(models.Model):
    name = models.CharField(_("Order category name"), max_length=249)

    def __str__(self):
        return self.name


class Order(IOrder):
    volunter = models.ForeignKey(
        "account.Volunter",
        verbose_name=_("Contractor"),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    is_taken = models.BooleanField(_("Is taken"), default=False)
    taked_at = models.DateTimeField(null=True, blank=True)

orders/views.py
from turtle import title
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views import generic

from account.models import Squad, Volunter
from .models import Category, Order
from django import forms


def index(request):
    context = {}
    if request.user.is_authenticated:
        context = {"redirect_path": reverse("fundraising:view")}

    return render(request, "index.html", context)


# ============ Orders section =========================


def order_view(request):
    return render(request, "orders/orders_view.html")


def take_order(request, pk):
    order = Order.objects.get(pk=pk)
    volunter_profile = Volunter.objects.get(pk=request.user.pk)
    order.volunter = volunter_profile
    order.is_taken = True
    order.taked_at = timezone.now()
    order.save()
    return HttpResponse("Упішно взято")


def untake_order(request, pk):
    order = Order.objects.get(pk=pk)
    order.volunter = None
    order.is_taken = False
    order.taked_at = None
    order.save()
    return HttpResponse("Упішно вилучено")


def remove_contractor(request, pk):
    order = Order.objects.get(pk=pk)
    order.volunter = None
    order.is_taken = False
    order.taked_at = None
    order.save()
    return HttpResponse("Упішно вилучено")


def mark_completed(request, pk):
    order = Order.objects.get(pk=pk)
    order.completed_at = timezone.now()
    order.is_completed = True
    order.save()
    return HttpResponse("Упішно виконано")


class OrdersCategoryListView(generic.ListView):
    model = Category
    template_name = "components/category.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["path"] = reverse("orders:list")
        return context


class OrdersListView(generic.ListView):
    paginate_by = settings.DEFAULT_PAGINATION
    model = Order
    template_name = "orders/list.html"

    def get_queryset(self):
        qs = Order.objects.filter(is_taken=False)
        filter_search = self.request.GET.get("search")
        filter_category = self.request.GET.get("category")
        filter_user = self.request.GET.get("initiator")
        if filter_search:
            qs = qs.filter(title__icontains=filter_search)
        if filter_category:
            qs = qs.filter(category__pk=filter_category)
        if filter_user:
            qs = qs.filter(squad__pk=filter_user)
        return qs


class OrdersDetailView(generic.DetailView):
    model = Order
    template_name = "orders/orders_detail.html"


class OrdersDeleteView(generic.DeleteView):
    model = Order
    template_name = "components/delete_form.html"
    success_url = reverse_lazy("orders:view")


class OrdersCreateView(generic.CreateView):
    model = Order
    template_name = "components/create_form.html"
    fields = ["title", "info", "category"]
    success_url = "/"

    def form_valid(self, form: forms.BaseModelForm) -> HttpResponse:
        order = form.instance
        order.squad = Squad.objects.get(user=self.request.user)
        return super(OrdersCreateView, self).form_valid(form)


class OrdersUpdateView(generic.UpdateView):
    model = Order
    template_name = "components/update_form.html"
    fields = ["title", "info", "category"]

    def get_success_url(self) -> str:
        obj = self.get_object()
        return reverse_lazy("orders:detail", kwargs={"pk": obj.pk})


class MyOrdersListView(OrdersListView):
    template_name = "my_orders/my_orders_list.html"

    def get_queryset(self):
        filter_search = self.request.GET.get("search")
        user = self.request.user
        qs = self.model.objects.all()
        role = user.get_role()
        if role == "Volunter":
            qs = qs.filter(volunter__pk=user.pk)
        elif role == "Squad":
            qs = qs.filter(squad__pk=user.pk)
        if filter_search:
            qs = qs.filter(title__icontains=filter_search)
        return qs


class MyOrdersDetailView(OrdersDetailView):
    template_name = "my_orders/my_orders_detail.html"


def my_orders_view(request):
    return render(request, "my_orders/my_orders_view.html")

templates/orders/list.html
<ul class="is-overflowed" id="side-ul">
    {%for order in object_list%}
        <li class="mb-2">
            <div class="card is-clickable p-2 card-hovered" hx-get="{%url 'orders:detail' pk=order.id%}" hx-target="#content-detail" hx-swap="innerHTML" hx-trigger="click">
                    <p class="title is-5">{{order.title}}</p>
                    <p class="subtitle is-6">{{order.info|truncatechars:40}}</p>
                    <div class="is-flex is-justify-content-space-between is-flex-direction-row is-align-items-flex-end">
                        <p>{{order.created_at|date:'d.m.Y'}}</p>
                        <a class="button is-text" hx-get="{%url 'account:squad-detail' pk=user.pk%}" hx-target="#content-detail" hx-swap="innerHTML">
                           <span class="mr-2">
                                <p>{{order.squad.squad_name}}</p>
                           </span>
                           <span>
                                <figure class="image is-32x32">
                                    <img class="is-rounded" src="{{order.squad.get_photo}}">
                                </figure>
                           </span>
                        </a>
                    </div>
            </div>
        </li>
    {%empty%}
        <p>Нажаль тут нічого немає</p>
    {%endfor%}
</ul>
{%if page_obj.has_next%}
    <button class="button is-primary" hx-get="{{request.path}}?page={{page_obj.next_page_number}}" hx-trigger="click" hx-swap="outerHTML" hx-targe="side-ul">Далі...</button>
{%endif%}

templates/orders/orders_category.html
<div class="is-flex is-flex-direction-column" style="overflow-y:auto;">
    <p class="subtitle is-5">По категоріям</p>
    {%for item in object_list%}
        <a 
        hx-get="{%url 'orders:list'%}?category={{item.pk}}" class="button has-text-left mb-2"
        hx-target="#side-menu" 
        hx-swap="innerHTML" >{{item.name}}</a>
        
    {%endfor%}
</div>

templates/orders/orders_detail.html
<div class="is-flex is-flex-direction-column is-justify-content-space-betwee container box mt-2">
    <div class="content">
        <p class="title">{{object.title}}</p>
        <p class="subtitle">{{object.info}}</p>
        <p class="subtitle">Категорія: <a hx-get="{%url 'orders:list'%}?category={{object.category.pk}}"
            hx-target="#side-menu" 
            hx-swap="innerHTML">{{object.category.name}}</a></p>
    </div>
    <div class="columns">
        <div class="content is-flex is-flex-direction-column column p-4">
            <div class="is-flex gap-10 is-align-items-center">
                <img class="is-rounded" src="{{order.squad.get_photo}}" height="64" width="64">
                <p>Автор: <a class="is-underlined" hx-get="{%url 'account:squad-detail' pk=object.squad.pk%}" hx-target="#content-detail" hx-swap="innerHTML">{{object.squad.squad_name}}</a></p>
            </div>
        </div>
        <div class="column is-3 p-4">
            <div class="is-flex gap-6 is-flex-direction-column ">
            {%if request.user.role.title == "Volunter"%}
                <a class="button is-primary" hx-get="{%url 'orders:take' pk=object.id%}">Взяти запит</a>
                <a class="button is-primary" hx-post="{%url 'chat:create' user_id=object.squad.pk%}" hx-target="#content-detail" hx-swap="innerHTML">Відкрити чат</a>
            {%endif%}
            {%if request.user.pk == order.squad.pk%}
                <a  hx-get="{%url 'orders:delete' pk=object.pk%}" 
                    hx-target="#place-for-modal" 
                    hx-swap="innerHTML"
                    class="button is-danger">Видалити запит</a>
                <a  hx-get="{%url 'orders:update' pk=object.pk%}" 
                    hx-target="#content-detail" 
                    hx-swap="innerHTML"
                    class="button is-info">Редагувати</a>
            {%endif%}
                
            </div>
        </div>
    </div>
    <div id="place-for-modal"></div>
    <p class="subtitle is-6 mt-2">{{object.created_at|date:'d.m.Y H:i'}}</p>
    
</div>

templates/orders/orders_view.html
<div class="columns">

  <div class="column is-2 is-hidden" id="filter-column">
    <div class="box mt-2">
      <p class="title is-5">Фільтр</p>
      <div id="filter"></div>
    </div>
  </div>
    <div class="column is-3 is-flex is-flex-direction-column">
            <div class="is-sticked box mt-2" style="z-index:10;">
                <div class="is-flex is-justify-content-space-evenly is-align-items-flex-start">
                  <p class="subtitle is-4 has-text-centered is-sticked">Запити</p>
                  <a class="button is-primary is-outlined" id="filter-button" onclick="toggleColumn('filter-column')"
                  hx-get="{%url 'orders:category'%}" 
                  hx-swap="innerHTML" 
                  hx-target="#filter">
                    <span class="icon is-small">
                      <i class="fa-solid fa-filter"></i>
                    </span>
                  </a>
                </div>
                
                <div class="field">
                    <p class="control has-icons-left">
                      <input class="input" type="text" placeholder="Пошук" hx-get="{%url 'orders:list'%}" 
                      name="search" 
                      hx-target="#side-menu"
                      hx-swap="innerHTML"
                      hx-trigger="keyup changed delay:1s">
                      <span class="icon is-small is-left">
                        <i class="fas fa-search"></i>
                      </span>
                    </p>
                  </div>
            </div>
            
            <aside id="side-menu" style="overflow-y:auto;" class="content-size">
                    <div hx-get="{%url 'orders:list'%}" hx-trigger="load" hx-target="#side-menu" hx-swap="innerHTML">
                    </div>
            </aside>
    </div>
    <div class="column content-column" id="content-detail" style="overflow-y:auto;">
        <div class="columns is-vcentered">
          <div class="has-text-centered column ">
            <p>Будь-ласка виберіть щось</p>
          </div>
        </div>
    </div>

    
</div>


<script>
  function toggleColumn(id){
    const col = document.getElementById(id)
    col.classList.toggle("is-hidden")
  }
</script>